[package]
name = "attestation-server"
version = "0.1.0"
authors = ["LKatalin"]
edition = "2018"

[dependencies]
sgx-isa = { version = "0.2", features = ["sgxstd"] }
ring = "0.16.5"

[patch.crates-io]
ring = { git = 'https://github.com/npmccallum/ring.git' }
